server:
  port: 8060 
# 数据源配置
spring:
  mail:
    host: smtp.qq.com # QQ邮箱smtp主机
    port: 587 #端口号465或587
    username: 517001426@qq.com
    password: mxjgmiqeyypubhhd  # 这里QQ邮箱开通POP3/SMTP提供的授权码，如果邮箱服务商没有授权码，可以使用密码代替
    protocol: smtp
    default-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
#     force是将request和response都设置字符集
      force: true
#     force单独设置request和response
#     force-response: true
#     force-request: false
  application:
    name: microservice-file
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC&useSSL=false
    username: root
    password: root
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，wall用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    intialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatement: true
    maxPreparedStatementPerConnectionSize: 20
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  #servlet:
   # multipart:
   #  max-file-size: 10000Mb
   #  max-request-size: 100000Mb
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #配置redis数据库链接
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis: 
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 20
        max-wait: 60000
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  path: D://mylog     #默认spring.log
  #level:
   # com.java.service: warn    #指定包下的日志级别为warn，warn级别以下的日志不打印
  #pattern:
  #  console: -%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
   # file: -%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
  # %d{HH:mm:ss.SSS}——日志输出时间
  # %thread——输出日志的进程名字，这在Web应用以及异步任务处理中很有用
  # %-5level——日志级别，并且使用5个字符靠左对齐
  # %logger- ——日志输出者的名字
  # %msg——日志消息
  # %n——平台的换行符